worker_processes auto;

events {
    worker_connections 1024;
}

http {
    upstream localhost {
        server blue-web:8081;
        # server green-web:8082;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://localhost;
            proxy_set_header Host $host;
        }
    }
}